export type Currency = {
  code: string;
  label: string;
};

// Liste ISO 4217 (devises actives). Ordonnée par code.
export const currencies: Currency[] = [
  { code: "AED", label: "Dirham des Émirats arabes unis" },
  { code: "AFN", label: "Afghani afghan" },
  { code: "ALL", label: "Lek albanais" },
  { code: "AMD", label: "Dram arménien" },
  { code: "ANG", label: "Florin antillais" },
  { code: "AOA", label: "Kwanza angolais" },
  { code: "ARS", label: "Peso argentin" },
  { code: "AUD", label: "Dollar australien" },
  { code: "AWG", label: "Florin arubais" },
  { code: "AZN", label: "Manat azerbaïdjanais" },
  { code: "BAM", label: "Mark convertible de Bosnie-Herzégovine" },
  { code: "BBD", label: "Dollar barbadien" },
  { code: "BDT", label: "Taka bangladais" },
  { code: "BGN", label: "Lev bulgare" },
  { code: "BHD", label: "Dinar bahreïni" },
  { code: "BIF", label: "Franc burundais" },
  { code: "BMD", label: "Dollar bermudien" },
  { code: "BND", label: "Dollar de Brunei" },
  { code: "BOB", label: "Boliviano bolivien" },
  { code: "BRL", label: "Réal brésilien" },
  { code: "BSD", label: "Dollar bahaméen" },
  { code: "BTN", label: "Ngultrum bhoutanais" },
  { code: "BWP", label: "Pula botswanais" },
  { code: "BYN", label: "Rouble biélorusse" },
  { code: "BZD", label: "Dollar bélizéen" },
  { code: "CAD", label: "Dollar canadien" },
  { code: "CDF", label: "Franc congolais" },
  { code: "CHF", label: "Franc suisse" },
  { code: "CLP", label: "Peso chilien" },
  { code: "CNY", label: "Yuan renminbi chinois" },
  { code: "COP", label: "Peso colombien" },
  { code: "CRC", label: "Colón costaricien" },
  { code: "CUP", label: "Peso cubain" },
  { code: "CVE", label: "Escudo cap-verdien" },
  { code: "CZK", label: "Couronne tchèque" },
  { code: "DJF", label: "Franc djiboutien" },
  { code: "DKK", label: "Couronne danoise" },
  { code: "DOP", label: "Peso dominicain" },
  { code: "DZD", label: "Dinar algérien" },
  { code: "EGP", label: "Livre égyptienne" },
  { code: "ERN", label: "Nakfa érythréen" },
  { code: "ETB", label: "Birr éthiopien" },
  { code: "EUR", label: "Euro" },
  { code: "FJD", label: "Dollar fidjien" },
  { code: "FKP", label: "Livre des Malouines" },
  { code: "FOK", label: "Couronne des Îles Féroé" },
  { code: "GBP", label: "Livre sterling" },
  { code: "GEL", label: "Lari géorgien" },
  { code: "GGP", label: "Livre de Guernesey" },
  { code: "GHS", label: "Cedi ghanéen" },
  { code: "GIP", label: "Livre de Gibraltar" },
  { code: "GMD", label: "Dalasi gambien" },
  { code: "GNF", label: "Franc guinéen" },
  { code: "GTQ", label: "Quetzal guatémaltèque" },
  { code: "GYD", label: "Dollar guyanien" },
  { code: "HKD", label: "Dollar de Hong Kong" },
  { code: "HNL", label: "Lempira hondurien" },
  { code: "HRK", label: "Kuna croate" },
  { code: "HTG", label: "Gourde haïtienne" },
  { code: "HUF", label: "Forint hongrois" },
  { code: "IDR", label: "Roupie indonésienne" },
  { code: "ILS", label: "Shekel israélien" },
  { code: "IMP", label: "Livre de l'Île de Man" },
  { code: "INR", label: "Roupie indienne" },
  { code: "IQD", label: "Dinar irakien" },
  { code: "IRR", label: "Rial iranien" },
  { code: "ISK", label: "Couronne islandaise" },
  { code: "JEP", label: "Livre de Jersey" },
  { code: "JMD", label: "Dollar jamaïcain" },
  { code: "JOD", label: "Dinar jordanien" },
  { code: "JPY", label: "Yen japonais" },
  { code: "KES", label: "Shilling kényan" },
  { code: "KGS", label: "Som kirghize" },
  { code: "KHR", label: "Riel cambodgien" },
  { code: "KID", label: "Dollar des Kiribati" },
  { code: "KMF", label: "Franc comorien" },
  { code: "KRW", label: "Won sud-coréen" },
  { code: "KWD", label: "Dinar koweïtien" },
  { code: "KYD", label: "Dollar des îles Caïmans" },
  { code: "KZT", label: "Tenge kazakh" },
  { code: "LAK", label: "Kip laotien" },
  { code: "LBP", label: "Livre libanaise" },
  { code: "LKR", label: "Roupie srilankaise" },
  { code: "LRD", label: "Dollar libérien" },
  { code: "LSL", label: "Loti lesothan" },
  { code: "LYD", label: "Dinar libyen" },
  { code: "MAD", label: "Dirham marocain" },
  { code: "MDL", label: "Leu moldave" },
  { code: "MGA", label: "Ariary malgache" },
  { code: "MKD", label: "Denar macédonien" },
  { code: "MMK", label: "Kyat du Myanmar" },
  { code: "MNT", label: "Tugrik mongol" },
  { code: "MOP", label: "Pataca macanaise" },
  { code: "MRU", label: "Ouguiya mauritanien" },
  { code: "MUR", label: "Roupie mauricienne" },
  { code: "MVR", label: "Rufiyaa maldivienne" },
  { code: "MWK", label: "Kwacha malawien" },
  { code: "MXN", label: "Peso mexicain" },
  { code: "MYR", label: "Ringgit malaisien" },
  { code: "MZN", label: "Metical mozambicain" },
  { code: "NAD", label: "Dollar namibien" },
  { code: "NGN", label: "Naira nigérian" },
  { code: "NIO", label: "Córdoba nicaraguayen" },
  { code: "NOK", label: "Couronne norvégienne" },
  { code: "NPR", label: "Roupie népalaise" },
  { code: "NZD", label: "Dollar néo-zélandais" },
  { code: "OMR", label: "Rial omanais" },
  { code: "PAB", label: "Balboa panaméen" },
  { code: "PEN", label: "Sol péruvien" },
  { code: "PGK", label: "Kina papou-néo-guinéenne" },
  { code: "PHP", label: "Peso philippin" },
  { code: "PKR", label: "Roupie pakistanaise" },
  { code: "PLN", label: "Złoty polonais" },
  { code: "PYG", label: "Guaraní paraguayen" },
  { code: "QAR", label: "Riyal qatari" },
  { code: "RON", label: "Leu roumain" },
  { code: "RSD", label: "Dinar serbe" },
  { code: "RUB", label: "Rouble russe" },
  { code: "RWF", label: "Franc rwandais" },
  { code: "SAR", label: "Riyal saoudien" },
  { code: "SBD", label: "Dollar des Îles Salomon" },
  { code: "SCR", label: "Roupie seychelloise" },
  { code: "SDG", label: "Livre soudanaise" },
  { code: "SEK", label: "Couronne suédoise" },
  { code: "SGD", label: "Dollar de Singapour" },
  { code: "SHP", label: "Livre de Sainte-Hélène" },
  { code: "SLE", label: "Leone sierra-léonais" },
  { code: "SOS", label: "Shilling somalien" },
  { code: "SRD", label: "Dollar surinamais" },
  { code: "SSP", label: "Livre sud-soudanaise" },
  { code: "STN", label: "Dobra santoméen" },
  { code: "SYP", label: "Livre syrienne" },
  { code: "SZL", label: "Lilangeni eswatinien" },
  { code: "THB", label: "Baht thaïlandais" },
  { code: "TJS", label: "Somoni tadjik" },
  { code: "TMT", label: "Manat turkmène" },
  { code: "TND", label: "Dinar tunisien" },
  { code: "TOP", label: "Pa'anga tongan" },
  { code: "TRY", label: "Livre turque" },
  { code: "TTD", label: "Dollar de Trinité-et-Tobago" },
  { code: "TVD", label: "Dollar de Tuvalu" },
  { code: "TWD", label: "Nouveau dollar taïwanais" },
  { code: "TZS", label: "Shilling tanzanien" },
  { code: "UAH", label: "Hryvnia ukrainienne" },
  { code: "UGX", label: "Shilling ougandais" },
  { code: "USD", label: "Dollar américain" },
  { code: "UYU", label: "Peso uruguayen" },
  { code: "UZS", label: "Sum ouzbek" },
  { code: "VED", label: "Bolívar numérique vénézuélien" },
  { code: "VES", label: "Bolívar vénézuélien" },
  { code: "VND", label: "Đồng vietnamien" },
  { code: "VUV", label: "Vatu vanuatais" },
  { code: "WST", label: "Tala samoan" },
  { code: "XAF", label: "Franc CFA BEAC" },
  { code: "XCD", label: "Dollar des Caraïbes orientales" },
  { code: "XOF", label: "Franc CFA BCEAO" },
  { code: "XPF", label: "Franc CFP" },
  { code: "YER", label: "Rial yéménite" },
  { code: "ZAR", label: "Rand sud-africain" },
  { code: "ZMW", label: "Kwacha zambien" },
  { code: "ZWL", label: "Dollar zimbabwéen" },
];
