# -*- coding: utf-8 -*-
{
    'name': 'Quelyos API',
    'version': '19.0.1.89.0',
    'category': 'Quelyos/API',
    'summary': 'API REST pour frontend e-commerce et backoffice',
    'author': 'Quelyos',
    'website': 'https://quelyos.com',
    'license': 'LGPL-3',
    'external_dependencies': {
        'python': ['qrcode', 'Pillow', 'faker'],
    },
    'depends': [
        'base',
        'mail',
        'sale_management',
        'stock',
        # OCA Stock modules (Odoo Community Association)
        # Note: OCA ≠ Odoo Core. Ces modules sont des extensions communautaires
        # indépendantes qui ne violent pas la règle d'isolation Quelyos/Odoo 19 base.
        'stock_inventory',
        'stock_warehouse_calendar',
        'website',
        'website_sale',
        'product',
        'account',
        'crm',
        'delivery',
        'payment',
        # HR modules natifs pour héritage (Community only)
        # TEMPORAIREMENT DÉSACTIVÉ : bug Odoo 19 hr_holidays (code NULL)
        # 'hr',
        # 'hr_holidays',
        # 'hr_attendance',
        # 'hr_skills',
        # GMAO (Maintenance Management) - DÉSACTIVÉ (module non disponible Odoo 19)
        # 'maintenance',
    ],
    'data': [
        'security/security.xml',
        'security/ir.rule.xml',
        'security/ticket_rules.xml',
        'security/ir.model.access.csv',
        'data/installer_data.xml',
        'data/subscription_sequence.xml',
        'data/cycle_count_sequence.xml',
        'data/stock_scrap_sequence.xml',
        'data/stock_reservation_sequence.xml',
        'data/payment_sequence.xml',
        'data/subscription_plan_data.xml',
        'data/default_admin_tenant.xml',
        # 'data/demo_tenants_data.xml',  # TEMPORAIREMENT DÉSACTIVÉ (conflit domaine localhost)
        'data/menu_data.xml',
        'data/payment_providers.xml',
        'data/ir_cron_stock_alerts.xml',
        'data/ir_cron_abandoned_cart.xml',
        # 'data/ir_cron_theme_payouts.xml',  # TEMPORAIREMENT DÉSACTIVÉ (erreur Python dans code)
        'data/ir_cron_subscriptions.xml',
        'data/ir_cron_auth_tokens.xml',
        'data/ir_cron_backup_schedules.xml',
        'data/ir_cron_reservations.xml',
        'data/ir_cron_sitemap_healthcheck.xml',
        'data/res_country_state_tn.xml',
        'data/email_templates_data.xml',
        'data/email_templates_subscriptions.xml',
        'data/sms_templates.xml',
        'data/email_builder_templates.xml',
        # 'data/hr_sequence.xml',  # TEMPORAIREMENT DÉSACTIVÉ
        'data/ticket_sequence.xml',
        'data/seed_sequence.xml',
        'data/sla_policies.xml',
        'data/maintenance_stages_data.xml',
        # 'data/email_template_satisfaction_request.xml',  # Créé via hooks.py (workaround validation XML)
        # 'data/pos_demo_data.xml',  # TEMPORAIREMENT DÉSACTIVÉ (debug installation)
        # 'data/store_demo_data.xml',  # TEMPORAIREMENT DÉSACTIVÉ (erreur ligne 196)
        'data/theme_data.xml',
        'views/subscription_views.xml',
        'views/subscription_plan_views.xml',
        'views/tenant_views.xml',
        'views/menu_views.xml',
        'views/menu_navigation_views.xml',
        'views/hero_slide_views.xml',
        'views/promo_banner_views.xml',
        'views/promo_message_views.xml',
        'views/trust_badge_views.xml',
        'views/theme_views.xml',
        'views/ai_unanswered_views.xml',
    ],
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
}
