# -*- coding: utf-8 -*-
{
    'name': 'Quelyos API',
    'version': '19.0.1.0.103',
    'category': 'Website',
    'summary': 'API REST pour frontend e-commerce et backoffice',
    'author': 'Quelyos',
    'website': 'https://quelyos.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'sale_management',
        'stock',
        'website',
        'website_sale',
        'product',
        'account',
        'crm',
        'delivery',
        'payment',
        # HR modules natifs pour héritage (Community only)
        'hr',
        'hr_holidays',
        'hr_attendance',
        'hr_skills',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/subscription_sequence.xml',
        'data/cycle_count_sequence.xml',
        'data/payment_sequence.xml',
        'data/subscription_plan_data.xml',
        'data/demo_tenants_data.xml',
        'data/menu_data.xml',
        'data/payment_providers.xml',
        'data/ir_cron_stock_alerts.xml',
        'data/ir_cron_abandoned_cart.xml',
        'data/res_country_state_tn.xml',
        'data/email_templates_data.xml',
        'data/hr_sequence.xml',
        'data/ticket_sequence.xml',
        'data/pos_demo_data.xml',
        'views/subscription_views.xml',
        'views/subscription_plan_views.xml',
        'views/tenant_views.xml',
        'views/menu_views.xml',
        'views/menu_navigation_views.xml',
        'views/hero_slide_views.xml',
        'views/promo_banner_views.xml',
        'views/promo_message_views.xml',
        'views/trust_badge_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
